using UnityEngine;

namespace Components
{
    public class ParallaxLayer : MonoBehaviour
    {
        public float parallaxFactor = 0.5f; // чем меньше значение, тем медленнее слой двигается
        private Transform cameraTransform;
        private Vector3 previousCameraPosition;

        void Start()
        {
            cameraTransform = Camera.main.transform;
            previousCameraPosition = cameraTransform.position;
        }

        void LateUpdate()
        {
            Vector3 delta = cameraTransform.position - previousCameraPosition;
            transform.position += new Vector3(delta.x * parallaxFactor, delta.y * parallaxFactor, 0);
            previousCameraPosition = cameraTransform.position;
        }
    }
}